<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>-586</X>
  <Y>550</Y>
  <VerticalWidth>240</VerticalWidth>
  <VerticalHeight>119</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF0F0F0F</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>24FFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF00CC36</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF52CC73</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5C52</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC1200</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFACACAC</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZUYWhvbWEAAIBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZUYWhvbWEAAC9CBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZUYWhvbWEAAIBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>False</ShowBestSegments>
    <AntiAliasing>False</AntiAliasing>
    <DropShadows>False</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>True</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>True</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>False</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>False</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAZUYWhvbWEAAIBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></TitleFont>
        <SingleLine>True</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>FF2A2A2A</BackgroundColor>
        <BackgroundColor2>FF131313</BackgroundColor2>
        <BackgroundGradient>Vertical</BackgroundGradient>
        <DisplayGameIcon>True</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>False</ShowVariables>
        <TextAlignment>0</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>69</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFAAAAAA</TimerColor>
        <BackgroundColor>00000000</BackgroundColor>
        <BackgroundColor2>FF222222</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.ComparisonTime.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Tenths</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <TimingMethod>Current Timing Method</TimingMethod>
        <Display2Rows>False</Display2Rows>
        <Type>FinalTime</Type>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.WorldRecord.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Display2Rows>False</Display2Rows>
        <CenteredText>False</CenteredText>
        <FilterRegion>False</FilterRegion>
        <FilterPlatform>False</FilterPlatform>
        <FilterVariables>False</FilterVariables>
        <FilterSubcategories>True</FilterSubcategories>
        <TimingMethod>Default for Leaderboard</TimingMethod>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.ScriptableAutoSplit.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <ScriptPath></ScriptPath>
        <Start>True</Start>
        <Reset>True</Reset>
        <CustomSettings />
      </Settings>
    </Component>
  </Components>
</Layout>
